### ISSUE TITLE
How a marketplace provider will earn?

### ISSUE THREAD

**Issue by comeonline** [kaymen99/MarketPlace-Dapp-V2#1]
How will a marketplace owner will earn?

**Comment by kaymen99** [comment]
All the fees collected from products sales or the stores creation fee are sent to the administration contract where the owner can withdraw them

**Comment by comeonline** [comment]
how and where to set the fee like 2%, 5% etc?

**Comment by kaymen99** [comment]
For the market and stores products the fee is set on a basis of 1000 (meaning fee = 50 => 5%), and it can be set by changing the following lines :

For the main market [here](https://github.com/kaymen99/MarketPlace-Dapp-V2/blob/main/contracts/Market.sol#L12)

For the store [here](https://github.com/kaymen99/MarketPlace-Dapp-V2/blob/main/contracts/Store.sol#L22)

For the auction market [here](https://github.com/kaymen99/MarketPlace-Dapp-V2/blob/main/contracts/AuctionMarket.sol#L12)
